Description: CZ AWS training lambda advance 
Parameters:
  AdvanceLambdaAName:
    Description: AdvanceLambdaName
    Default: cz-lambdaA
    Type: String
  CodeBucket:
    Description: Where your lambda code in
    Type: String
  LambdaAFileName:
    Description:  your lambda file name
    Type: String
  LambdaBFileName:
    Description:  your lambda file name
    Type: String
  
Resources:
  CZAdvanceLambdaA:
    Type: AWS::Lambda::Function
    Properties:
      Code: 
        S3Bucket: !Ref CodeBucket # just the bucket name such as: 
        S3Key: !Ref LambdaAFileName
      FunctionName: !Ref AdvanceLambdaAName 
      Description: LambdaA
      Handler: czLambdaA.handler ## todo
      Runtime: nodejs12.x
      Role: arn:aws:iam::494526681395:role/for-aws-training    

  CZAdvanceLambdaB:
    Type: AWS::Lambda::Function
    Properties:
      Code: 
        S3Bucket: !Ref CodeBucket # just the bucket name such as: 
        S3Key: !Ref LambdaBFileName
      FunctionName: cz-lambdaB 
      Description: LambdaB
      Handler: czLambdaB.handler ## todo
      Runtime: nodejs12.x
      Role: arn:aws:iam::494526681395:role/for-aws-training    
