Description: CZ AWS training lambda 
Parameters:
  SampleLambdaName:
    Description: SampleLambdaName
    Default: cz-hello-world-lambda
    Type: String
  ABucketName:
    Description: ABucketName
    Default: cz-a-bucket
    Type: String
  CodeBucket:
    Description: Where your lambda code in
    Type: String
  LambdaFileName:
    Description:  your lambda file name
    Type: String
  
Resources:
  CZSampleLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code: 
        S3Bucket: !Ref CodeBucket # just the bucket name such as: 
        S3Key: !Ref LambdaFileName
      FunctionName: !Ref SampleLambdaName 
      Description: say HelloWorld
      Handler: index.handler ## todo
      Runtime: nodejs12.x
      Role: arn:aws:iam::494526681395:role/for-aws-training

  CZABucket:
    Type: AWS::S3::Bucket
    DependsOn:
      - CZSampleLambda
    Properties:
      BucketName: !Ref ABucketName
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Function: !GetAtt CZSampleLambda.Arn

  S3InvokeRole:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt CZSampleLambda.Arn
      Principal: s3.amazonaws.com      
